### ISSUE TITLE
Stub Return Sequence for a while loop

### ISSUE THREAD

**Issue by markj9** [davidvilla/python-doublex#1]
Is it possible to stub a method return sequence so that a while loop will run a specific number of times with specific return values?  It appears to always return the last return specified. 

This stub always returns true so a while loop in the SUT is never executing:
`task = Stub()
when(task).is_done().returns(False).times(1)
when(task).is_done().returns(True).times(1)`

**Comment by davidparsson** [comment]
Yes, see `.delegates()`: https://python-doublex.readthedocs.io/en/latest/delegates.html
