### ISSUE TITLE
New release, please

### ISSUE THREAD

**Issue by davidparsson** [davidvilla/python-doublex#16]
@davidvilla, I'd appreciate if you could make a new release.

A recap of the changes from #8, #10, #11, #12, #13, #14, #17, #20, #21:
- drops support for Python versions past end-of-life (<= 3.5)
- fixes tests and removes deprecation warnings for supported Python versions (3.6 – 3.10)
- fixes issues introduced in Python 3.8+
- support specifying behaviour for `@classmethod` methods

**Comment by davidparsson** [comment]
@davidvilla, is it time to reconsider our strategy for publishing releases as well?

**Comment by davidparsson** [comment]
Hi @davidvilla. It has been another 7 months. Could you perhaps instruct me on how to perform releases, and grant me the permissions to do so? If not, I fear we're at the point where we need to publish a fork.

**Comment by davidparsson** [comment]
Hi @davidvilla. We're at road's end here, so unless we hear from you in a few weeks we'll be making a public fork under a new name.

**Comment by hartwork** [comment]
@davidvilla any thoughts?
@davidparsson there is also https://peps.python.org/pep-0541/#how-to-request-a-name-transfer for some cases, not sure if applicable/realistic here.

**Comment by davidparsson** [comment]
I've tried to reach out to @davidvilla on email directly, and I'll give him a bit of time to reply before moving forward.

**Comment by hartwork** [comment]
@davidparsson good idea! :+1:

**Comment by davidvilla** [comment]
Hi:

Sorry guys. I will get my hands on this subject tomorrow.

Cheers

**Comment by davidvilla** [comment]
Can I release repository head as release 1.9.4?

@davidparsson do you prefer to make releases on your own? I dont known if this is possible with Pypi.

**Comment by davidvilla** [comment]
Released as 1.9.6

**Comment by davidparsson** [comment]
I'm not sure how to interpret [semantic versioning](https://semver.org) when dropping support for old runtimes, but the API is backwards-compatible. I would either release this as 1.10.0 (since new functionality is introduced) or 2.0.0 (since the support for old python runtimes is dropped, and may be considered backwards-incompatible).

I'd like to be able to make releases, yes. I'm quite sure this is possible, but I haven't found how. This is my public profile on PyPi: https://pypi.org/user/david.parsson/

**Comment by davidvilla** [comment]
I'm of the same opinion, I don't know if stopping support is the same as breaking the API, I guess not. I guess you would have to move to 2.0 when implementing something that effectively breaks support for older Python versions.

I am going to try adding several authors to the setup.py. Please give me the email address you use as login in PyPI.

**Comment by davidparsson** [comment]
I've sent you an email.

**Comment by davidparsson** [comment]
Thank you!

**Comment by hartwork** [comment]
@davidvilla @davidparsson you can have multiple maintainers in PyPI per project 100%, the page to add new people should be https://pypi.org/manage/project/doublex/collaboration/ . The authors in `setup.py` is cosmetic but also nice to have :+1:

**Comment by hartwork** [comment]
Just saw you were already successful. Nevermind then :smiley:

**Comment by hartwork** [comment]
I'd like to note that 1.9.6.1 is rather unusual in a semver world, my vote for sticking to three parts like 1.9.7, should be enough for 99% of cases.

Regarding compatibility when dropping support for older Python: If the new version has `python_requires` bumped, incompatible versions of Python will not be see that release and not be able to install it, so technically there is no breakage for anyone, and hence no bump in major version is needed. Many projects still do that, but not because it's needed.

**Comment by hartwork** [comment]
PS: Gentoo already bumped to 1.9.6.1 at https://github.com/gentoo/gentoo/commit/7abce79dce6d979523e69403af0907819259304d and it allowed reducing downstream patch count. Thank you! :+1:
