### ISSUE TITLE
Python 3.5 Type Hints breaks return value specifications

### ISSUE THREAD

**Issue by davidparsson** [davidvilla/python-doublex#4]
I'm unable to define behavior for stubs/spies/mocks having [Python 3.5 type hints](https://www.python.org/dev/peps/pep-0484/). Invoking `returns(...)` fails with the following error:

      # ...
      File "/Users/me/.virtualenvs/dev/lib/python3.5/site-packages/doublex/proxy.py", line 53, in get_signature
        return MethodSignature(self, method_name)
      File "/Users/me/.virtualenvs/dev/lib/python3.5/site-packages/doublex/proxy.py", line 181, in __init__
        self.argspec = inspect.getargspec(self.method)
      File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/inspect.py", line 1045, in getargspec
        raise ValueError("Function has keyword-only arguments or annotations"
    ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them

Running this minimal example on Python 3.5 reproduces this:

    import doublex

    class MyClass:
        def get_name(self) -> str:
            return 'a name'

    with doublex.Stub(MyClass) as my_class:
        my_class.get_name().returns('another name')

A simple solution seems to be to wrap the `getargspec()` call in a try-except:

    try:
        self.argspec = inspect.getargspec(self.method)
    except ValueError:
        self.argspec = inspect.getfullargspec(self.method)

**Comment by davidvilla** [comment]
Hi:

Your wrapper makes the job. It will be included in next release 1.8.3 (today).

Thanks a lot

**Comment by davidparsson** [comment]
Great! Thanks a million for a quick resolution!
