### ISSUE TITLE
Stub observers documentation and example

### ISSUE THREAD

**Issue by danibaena** [davidvilla/python-doublex#6]
Hello David, I was reading the doublex documentation, and I really don't see clearly how to use stub observers intead of unittest.mock side_effects. Could you or someone provide an example of how are stub observers used?

My goal is to use stub observers to get the same behaviour as in:

https://docs.python.org/3/library/unittest.mock.html#quick-guide

More specific like this:

```
>>> mock.side_effect = [5, 4, 3, 2, 1]
>>> mock(), mock(), mock()
(5, 4, 3)
```

**Comment by davidparsson** [comment]
See `.delegates()`: https://python-doublex.readthedocs.io/en/latest/delegates.html
